version:

options:
  check-update: true
  console-message: true

economy:
  currencySymbol: '$'

bag-item:
  enabled: true
  minimalAmount: 1000
  maximalAmount: 100000

gift-item:
  enabled: true
  minimalAmount: 1000
  maximalAmount: 100000