name: WEconomy
version: 0.0.6
description: WEconomy
main: fr.ward.weconomy.WEconomy
author: Ward
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  economy:
    description: Main command
    usage: /economy
    aliases: [eco]